/* the START column has the icd 9 dx; same INPATIENT_ELX_GRP dataset's 
ICD9_DGNS_CD_1 ICD9_DGNS_CD_2 ICD9_DGNS_CD_3 ICD9_DGNS_CD_4 ICD9_DGNS_CD_5
ICD9_DGNS_CD_6 ICD9_DGNS_CD_7 ICD9_DGNS_CD_8 ICD9_DGNS_CD_9 ICD9_DGNS_CD_10*/

/* -----County Separation------
Determine the states and counties of the cohort I want to analyze (CA, NY)
Once that is filtered out, make sure I have a cohort of at least a few thousands
Then I will continue filtering based on diagnosis */

Libname CMS "/courses/dd667415ba27fe300/MEDICARE_DESYNPUF" access=readonly ;

DATA BENE1;
SET CMS.BENE_09_10;
RUN;

/* DATA SET HAS 687,502 TOTAL */
PROC MEANS DATA=BENE1; RUN;

/* Variables available = BENE_BIRTH_DT BENE_COUNTY_CD BENE_DEATH_DT BENE_ESRD_IND BENE_RACE_CD BENE_SEX_IDENT_CD
BENRES_CAR BENRES_IP BENRES_OP DESYNPUF_ID MEDREIMB_IP PPPYMT_CAR PPPYMT_IP SP_STATE_CODE
SP_ALZHDMTA SP_CHF SP_CHRNKIDN SP_CNCR SP_COPD SP_DEPRESSN SP_DIABETES SP_ISCHMCHT SP_OSTEOPRS SP_RA_OA SP_STRKETIA */
PROC CONTENTS DATA= BENE1 POSITION SHORT; RUN;

/* frequency by chronic condition*/
PROC FREQ DATA=BENE1;
TABLE SP_ALZHDMTA SP_CHF SP_CHRNKIDN SP_CNCR SP_COPD SP_DEPRESSN SP_DIABETES SP_ISCHMCHT SP_OSTEOPRS SP_RA_OA SP_STRKETIA;
RUN;

/* frequency by state and county
05 is CA and 33 is NY*/
PROC FREQ DATA=BENE1;
TABLE BENE_COUNTY_CD SP_STATE_CODE;
RUN;
/*CA OR 05 HAS 59,699 ENTRIES. NY OR 33 HAS 38,509*/

DATA BENE2;
SET CMS.INPATIENT_ELX_GRP;
RUN;

/*COUNT RECORDS IN BENEFICIARY SUMMARY*/
PROC SQL;
SELECT COUNT (*)
FROM CMS.BENE_09_10;
QUIT;
/*687,502*/

/*----------------CREATE TABLE FOR CALIFORNIA----------------*/
PROC SQL;
CREATE TABLE STATE_COUNTY AS
SELECT *
FROM CMS.BENE_09_10
WHERE SP_STATE_CODE="05"
ORDER BY BENE_COUNTY_CD;
QUIT;

/*COUNT RECORDS IN STATE_COUNTY TABLE*/
PROC SQL;
SELECT COUNT (*)
FROM STATE_COUNTY;
QUIT;
/*59,699*/

PROC CONTENTS DATA=STATE_COUNTY;RUN;

/*COUNTS THE NUMBER OF ENTRIES IN EACH COUNTY*/
PROC SQL;
CREATE TABLE COUNTY_COUNTING AS
SELECT BENE_COUNTY_CD, COUNT(BENE_COUNTY_CD) AS COUNTY_COUNT
FROM STATE_COUNTY
GROUP BY 1;
QUIT;

/*COUNTS THE NUMBER OF DISTINCT COUNTIES --NEED AT LEAST 75 COUNTIES FOR ANALYSIS*/
PROC SQL;
SELECT COUNT(DISTINCT BENE_COUNTY_CD)
FROM STATE_COUNTY;
QUIT;
/*60 DISTINCT COUNTIES IN CA OR 05*/

/*----------------------CREATING TABLE FOR NY------------------------------*/
/**/
PROC SQL;
CREATE TABLE STATE_COUNTY2 AS
SELECT *
FROM CMS.BENE_09_10
WHERE SP_STATE_CODE="33"
ORDER BY BENE_COUNTY_CD;
QUIT;

/*COUNT RECORDS IN STATE_COUNTY TABLE*/
PROC SQL;
SELECT COUNT (*)
FROM STATE_COUNTY2;
QUIT;
/*38,509*/

/*COUNTS THE NUMBER OF DISTINCT COUNTIES -- 60 + 62 = 122 COUNTIES TOTAL --- REACHED COUNTY NUMBER REQUIREMENT!!*/
PROC SQL;
SELECT COUNT(DISTINCT BENE_COUNTY_CD)
FROM STATE_COUNTY2;
QUIT;
/*62 DISTINCT COUNTIES IN NY OR 33*/

/*CONCATENATE CA AND NY TABLES TO ONE TABLE*/
DATA concat;
SET STATE_COUNTY
 STATE_COUNTY2;
RUN;
/*98,208 TOTAL; CALCULATION IS CORRECT WHEN ADDITION OF CA AND NY RECORD COUNTS*/


/*NEED TO COMBINE EACH ID INTO ONE RECORD BEFORE MERGING TABLES*/
/*MERGES CONCAT AND INPATIENT DATASETS*/
PROC SQL;
CREATE TABLE ST_COUNTY AS
SELECT A.DESYNPUF_ID, A.BENE_DEATH_DT, A.BENE_SEX_IDENT_CD, A.BENE_COUNTY_CD, A.SP_STATE_CODE,
A.SP_ALZHDMTA, A.SP_CHF, A.SP_CHRNKIDN, A.SP_CNCR, A.SP_COPD, A.SP_DEPRESSN, A.SP_DIABETES,
A.SP_ISCHMCHT, A.SP_OSTEOPRS, A.SP_RA_OA, A.SP_STRKETIA,
B.CLM_ADMSN_DT, B.NCH_BENE_DSCHRG_DT,
B.ICD9_DGNS_CD_1, B.ICD9_DGNS_CD_2, B.ICD9_DGNS_CD_3, B.ICD9_DGNS_CD_4, B.ICD9_DGNS_CD_5,
B.ICD9_DGNS_CD_6, B.ICD9_DGNS_CD_7, B.ICD9_DGNS_CD_8, B.ICD9_DGNS_CD_9, B.ICD9_DGNS_CD_10
FROM CONCAT AS A
LEFT JOIN CMS.INPATIENT_ELX_GRP AS B
ON A.DESYNPUF_ID = B.DESYNPUF_ID;
QUIT;

/*COUNT THE NUMBER OF DISTINCT BENEFICIARY*/
PROC SQL;
SELECT COUNT(DISTINCT DESYNPUF_ID)
FROM ST_COUNTY;
QUIT;
/*33,230*/


/*METHOD OF COMBINING MULTIPLE RECORDS INTO ONE ROW */
proc sql;
create table test2 as
select DESYNPUF_id, BENE_COUNTY_CD,
max(BENE_DEATH_DT) as DEATH_DATE,
MAX(BENE_SEX_IDENT_CD) AS GENDER,
MAX(BENE_COUNTY_CD) AS COUNTY_CODE,
MAX(SP_STATE_CODE) AS STATE_CODE,
MAX(SP_ALZHDMTA) AS ALZHEIMERS,
MAX(SP_CHF) AS CHF,
MAX(SP_CHRNKIDN) AS KIDNEY_DISEASE,
MAX(SP_CNCR) AS CANCER,
MAX(SP_COPD) AS COPD,
MAX(SP_DEPRESSN) AS DEPRESSION,
MAX(SP_DIABETES) AS DIABETES,
MAX(SP_ISCHMCHT) AS ISCHMCHT,
MAX(SP_OSTEOPRS) AS OSTEOPOROSIS,
MAX(SP_RA_OA) AS RA_OA,
MAX(SP_STRKETIA) AS STROKE,
MAX(CLM_ADMSN_DT) AS ADMISSION_DATE,
MAX(NCH_BENE_DSCHRG_DT) AS DISCHARGE_DATE,
MAX(ICD9_DGNS_CD_1) AS ICD9_DGNS_CD_1,
MAX(ICD9_DGNS_CD_2) AS ICD9_DGNS_CD_2,
MAX(ICD9_DGNS_CD_3) AS ICD9_DGNS_CD_3,
MAX(ICD9_DGNS_CD_4) AS ICD9_DGNS_CD_4,
MAX(ICD9_DGNS_CD_5) AS ICD9_DGNS_CD_5,
MAX(ICD9_DGNS_CD_6) AS ICD9_DGNS_CD_6,
MAX(ICD9_DGNS_CD_7) AS ICD9_DGNS_CD_7,
MAX(ICD9_DGNS_CD_8) AS ICD9_DGNS_CD_8,
MAX(ICD9_DGNS_CD_9) AS ICD9_DGNS_CD_9,
MAX(ICD9_DGNS_CD_10) AS ICD9_DGNS_CD_10
from ST_COUNTY
group by DESYNPUF_id, BENE_COUNTY_CD;
quit;
/*CONFIRMS THAT THIS STEP MATCHES THE COUNT OF DISTINCT BENEFICIARIES ---- 33,230 ---- AND METHOD WORKS */

/*TIME TO USE GROUPERS*/
/*FIRST SET UP LIBRARY*/
LIBNAME GRP "/courses/dd667415ba27fe300/GROUPERS" access=readonly ;

/*SECOND DEFINE YOUR DATASET*/
DATA GROUPER;
SET GRP.CCS_MULTI_DX;
RUN;

/*THIRD COMBINE VARIABLES BASED ON ICD9 CODE*/
PROC SQL;
CREATE TABLE test3 AS
SELECT *
FROM test2 AS A
LEFT JOIN grouper AS B
ON A.icd9_dgns_cd_1 = B.start;
QUIT;
